### ISSUE TITLE
Configure Eureka to handle requests and responses for micro-services.

### ISSUE THREAD

**Issue by okanmenevseoglu** [swe574-group2/swe574#51]
- Currently we can access to the methods from both 8080 and 8081 ports. However, with Eureka, we can also access our controllers from 1111 ports. (Ex.: localhost:1111/annotation and localhost:8080/annotation gives same results).
- We must design the system in a way that request should follow the following order:
**Client->Incoming Request->Eureka->Security->Annotation->Output response->Eureka?->Client**
- Research about Eureka and micro-service architecture are needed.

**Comment by penumbram-zz** [comment]
[This repo](https://github.com/steve-oakey/eureka-security-example) should give us an idea. For some reason, I'm getting different responses for GET localhost:8080/annotation and GET localhost:1111/annotation .

**Comment by ardaofluoglu** [comment]
When you first start the server and make a GET request to both:
localhost:8080/annotation
localhost:1111/annotation
then you should be seeing an empty list returned.

If you make a POST to either server, than a GET on that server should return you a non-empty list. The other server will still return an empty list.

**Comment by okanmenevseoglu** [comment]
@ardaofluoglu @penumbram Yes, now I checked again and it seems that somehow we have 2 annotation databases, one works from 1111 and one works from 8080. That is a weird problem.

**Comment by penumbram-zz** [comment]
@okanmenevseoglu maybe we don't need to run the separate application at all. running the EurekaCatPlugInService applicaton works both services on port 1111 and 8080/8081 don't respond, which can be the behaviour we're looking for, can't it? (not sure what a micro service would look like)

**Comment by penumbram-zz** [comment]
Regarding commit [90e7089](https://github.com/swe574-group2/swe574/commit/90e7089f5ba07ac82a0071ba5691157a0f120a21):

- Fixes the duplicate servers problem (Now port 1111 does not respond, only the relevant port to the microservice (i.e. 8080 for annotation micro service) is responsive.)
- Adds Discovery Client login for Eureka instances (localhost:1111 now requires the username: admin and password: 123456 denoted in eureka-server.yml)
- EnableWebSecurity now works, Booting the apps, starting with Eureka server and moving to the clients, everything should seem in order to everyone. @okanmenevseoglu @ardaofluoglu @gr3ysky
