### ISSUE TITLE
UI for textual tags has several (varying) icons after creation

### ISSUE THREAD

**Issue by uskudarli** [swe574-group2/swe574#79]
I have seen this bug before. But it doesn't seem to an open bug.

I don't know what that icon is for? What to do with it? And, did you figure out why several duplications occur?

**Comment by penumbram-zz** [comment]
It was designed by the front-enders to indicate how many people  annotated the text. For instance, if 3 different users annotate a text. It should show "3". If I remember correctly, the duplications were there at the presentation too, but I'm guessing nobody dared to debug. I'll try to fix it ASAP.

**Comment by uskudarli** [comment]
Right, it was like that in the demo also. I have not understood why sometimes it is 3 or 4. Could not reliably duplicate. It seems random, surely it is not.

@gr3ysky was imagining he may fix it... but probably did not dare as you said.

**Comment by penumbram-zz** [comment]
As you can see in the image below, it's fixed and now it's only showing 1 badge to indicate the number of annotations at a specific area. If you click on the red line boxing an annotation, It'll list the annotations in the CAT panel to the right. This one is showing the annotations I made for the term "societal demise".

<img width="1055" alt="screen shot 2017-01-07 at 20 28 28" src="https://cloud.githubusercontent.com/assets/8571749/21743713/8f403082-d510-11e6-80c6-58ca698a76c1.png">

**Comment by uskudarli** [comment]
Looks nice. But, when I visit that page I do not see any annotations. Neither annotations shows.

This is an interesting problem. I did not intentionally choose a nasty source. I thought it was an interesting blog to annotate. 

Don't worry about it.

**Comment by uskudarli** [comment]
Did we conflate the problems of medium with the marks indicating number of annotations? If so sorry. 

I think I need to update my plugin, sorry. Let me do that and test.

**Comment by uskudarli** [comment]
OK. Updated.

Now the extra icons don't appear. The number "1" stays constant. There is something off about what is being shown on the side. My observation is that the last annotation created doesn't show up on the list.

I have 4 annotations on our puppies test page. (not giving full link here, but you know it)

**Comment by penumbram-zz** [comment]
@uskudarli I think I understand what you mean, I'll investigate further.

**Comment by penumbram-zz** [comment]
Before the commit above, it wasn't possible to update a badge (the number of annotations for a target selector shown in the bottom right). Now it looks okay, though It's hard call it a minor issue, since it had its roots in 2 different realms of problem. First, once shown, the changed html wasn't open to update, and that was a deal breaker for updating "1" to "2". Second, an AJAX call was being treated as if it was a synchronous call, which is never the case with AJAX (AJAX calls are by definition async).

Apart from that, I found out that "abc" and "abc " were treated differently. Which was causing a UX issue since it's quite likely for a user to select the whitespace before or after a word. Looks like it's fixed now, the whitespace is trimmed at the time of insertion and the selector's start-end indexes are updated accordingly.

**Comment by penumbram-zz** [comment]
@uskudarli I believe this is resolved, isn't it? Is there anything to improve? If not, shall we close this last issue?

**Comment by uskudarli** [comment]
Yes, it is. Thank you.

**Comment by penumbram-zz** [comment]
@uskudarli Before you go, how about we set up a social for a coffee/drink to celebrate the end of our project?

What do you say? @gr3ysky @ardaofluoglu @okanmenevseoglu @seydakaradag @skanca 
Maybe group 1 would like to join too?

**Comment by uskudarli** [comment]
Go where? :) I am always here.

Sure. After grades submission, would be my pleasure.

**Comment by gr3ysky** [comment]
I can join :)
